Finished

diff --git a/mvnw b/mvnw
--- a/mvnw
+++ b/mvnw
@@ -155,7 +155,7 @@ fi
 
 if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA_HOME is not defined correctly." >&2
-  echo "  We cannot execute $JAVACMD" >&2
+  echo "   cannot execute $JAVACMD" >&2
   exit 1
 fi
 
